import 'package:flutter/material.dart';

/// Katalog JSON'larında isimle referans verilen ikonlar.
/// `AppIcons.get('flight')` -> Icons.flight ; bilinmeyen isim -> Icons.category
class AppIcons {
  AppIcons._();

  static const Map<String, IconData> _map = {
    'ac_unit': Icons.ac_unit,
    'account_balance_wallet': Icons.account_balance_wallet,
    'airline_seat_recline_extra': Icons.airline_seat_recline_extra,
    'airport_shuttle': Icons.airport_shuttle,
    'anchor': Icons.anchor,
    'apartment': Icons.apartment,
    'assignment': Icons.assignment,
    'attractions': Icons.attractions,
    'baby_changing_station': Icons.baby_changing_station,
    'backpack': Icons.backpack,
    'badge': Icons.badge,
    'bakery_dining': Icons.bakery_dining,
    'battery_charging_full': Icons.battery_charging_full,
    'beach_access': Icons.beach_access,
    'bed': Icons.bed,
    'bolt': Icons.bolt,
    'book': Icons.book,
    'brush': Icons.brush,
    'build': Icons.build,
    'business_center': Icons.business_center,
    'cabin': Icons.cabin,
    'cake': Icons.cake,
    'calendar_month': Icons.calendar_month,
    'car_repair': Icons.car_repair,
    'card_giftcard': Icons.card_giftcard,
    'casino': Icons.casino,
    'category': Icons.category,
    'celebration': Icons.celebration,
    'chair': Icons.chair,
    'checklist': Icons.checklist,
    'checkroom': Icons.checkroom,
    'child_care': Icons.child_care,
    'child_friendly': Icons.child_friendly,
    'church': Icons.church,
    'cleaning_services': Icons.cleaning_services,
    'coffee': Icons.coffee,
    'computer': Icons.computer,
    'construction': Icons.construction,
    'cookie': Icons.cookie,
    'credit_card': Icons.credit_card,
    'cruelty_free': Icons.cruelty_free,
    'currency_lira': Icons.currency_lira,
    'delete_sweep': Icons.delete_sweep,
    'description': Icons.description,
    'devices': Icons.devices,
    'directions_bike': Icons.directions_bike,
    'directions_boat': Icons.directions_boat,
    'directions_bus': Icons.directions_bus,
    'directions_car': Icons.directions_car,
    'diversity_3': Icons.diversity_3,
    'done_all': Icons.done_all,
    'downhill_skiing': Icons.downhill_skiing,
    'dry_cleaning': Icons.dry_cleaning,
    'eco': Icons.eco,
    'egg': Icons.egg,
    'elderly': Icons.elderly,
    'electrical_services': Icons.electrical_services,
    'emoji_events': Icons.emoji_events,
    'event': Icons.event,
    'event_note': Icons.event_note,
    'explore': Icons.explore,
    'extension': Icons.extension,
    'face': Icons.face,
    'face_3': Icons.face_3,
    'fact_check': Icons.fact_check,
    'family_restroom': Icons.family_restroom,
    'favorite': Icons.favorite,
    'festival': Icons.festival,
    'fitness_center': Icons.fitness_center,
    'flag': Icons.flag,
    'flashlight_on': Icons.flashlight_on,
    'flight': Icons.flight,
    'flight_takeoff': Icons.flight_takeoff,
    'forest': Icons.forest,
    'garage': Icons.garage,
    'grass': Icons.grass,
    'groups': Icons.groups,
    'handyman': Icons.handyman,
    'headphones': Icons.headphones,
    'healing': Icons.healing,
    'health_and_safety': Icons.health_and_safety,
    'help_outline': Icons.help_outline,
    'hiking': Icons.hiking,
    'holiday_village': Icons.holiday_village,
    'home': Icons.home,
    'home_repair_service': Icons.home_repair_service,
    'home_work': Icons.home_work,
    'inventory_2': Icons.inventory_2,
    'kebab_dining': Icons.kebab_dining,
    'iron': Icons.iron,
    'kayaking': Icons.kayaking,
    'key': Icons.key,
    'kitchen': Icons.kitchen,
    'landscape': Icons.landscape,
    'lightbulb': Icons.lightbulb,
    'liquor': Icons.liquor,
    'list_alt': Icons.list_alt,
    'move_to_inbox': Icons.move_to_inbox,
    'local_bar': Icons.local_bar,
    'local_drink': Icons.local_drink,
    'local_florist': Icons.local_florist,
    'local_hospital': Icons.local_hospital,
    'local_laundry_service': Icons.local_laundry_service,
    'local_pizza': Icons.local_pizza,
    'local_shipping': Icons.local_shipping,
    'location_city': Icons.location_city,
    'lock': Icons.lock,
    'luggage': Icons.luggage,
    'lunch_dining': Icons.lunch_dining,
    'man': Icons.man,
    'map': Icons.map,
    'medical_information': Icons.medical_information,
    'medical_services': Icons.medical_services,
    'menu_book': Icons.menu_book,
    'more_horiz': Icons.more_horiz,
    'mosque': Icons.mosque,
    'movie': Icons.movie,
    'music_note': Icons.music_note,
    'nightlife': Icons.nightlife,
    'nightlight': Icons.nightlight,
    'note_alt': Icons.note_alt,
    'outdoor_grill': Icons.outdoor_grill,
    'paid': Icons.paid,
    'palette': Icons.palette,
    'park': Icons.park,
    'pending_actions': Icons.pending_actions,
    'people': Icons.people,
    'person': Icons.person,
    'pets': Icons.pets,
    'photo_camera': Icons.photo_camera,
    'pool': Icons.pool,
    'pregnant_woman': Icons.pregnant_woman,
    'public': Icons.public,
    'ramen_dining': Icons.ramen_dining,
    'receipt_long': Icons.receipt_long,
    'recycling': Icons.recycling,
    'redeem': Icons.redeem,
    'restaurant': Icons.restaurant,
    'rice_bowl': Icons.rice_bowl,
    'rocket_launch': Icons.rocket_launch,
    'rule': Icons.rule,
    'sailing': Icons.sailing,
    'sanitizer': Icons.sanitizer,
    'scuba_diving': Icons.scuba_diving,
    'savings': Icons.savings,
    'school': Icons.school,
    'science': Icons.science,
    'security': Icons.security,
    'self_improvement': Icons.self_improvement,
    'set_meal': Icons.set_meal,
    'shopping_bag': Icons.shopping_bag,
    'shopping_cart': Icons.shopping_cart,
    'smartphone': Icons.smartphone,
    'soap': Icons.soap,
    'spa': Icons.spa,
    'sports_basketball': Icons.sports_basketball,
    'sports_esports': Icons.sports_esports,
    'sports_golf': Icons.sports_golf,
    'sports_soccer': Icons.sports_soccer,
    'sports_volleyball': Icons.sports_volleyball,
    'sports_tennis': Icons.sports_tennis,
    'star': Icons.star,
    'sticky_note_2': Icons.sticky_note_2,
    'store': Icons.store,
    'storefront': Icons.storefront,
    'stroller': Icons.stroller,
    'subscriptions': Icons.subscriptions,
    'surfing': Icons.surfing,
    'table_restaurant': Icons.table_restaurant,
    'task': Icons.task,
    'task_alt': Icons.task_alt,
    'temple_buddhist': Icons.temple_buddhist,
    'terrain': Icons.terrain,
    'theater_comedy': Icons.theater_comedy,
    'today': Icons.today,
    'toys': Icons.toys,
    'train': Icons.train,
    'two_wheeler': Icons.two_wheeler,
    'vaccines': Icons.vaccines,
    'videocam': Icons.videocam,
    'villa': Icons.villa,
    'volunteer_activism': Icons.volunteer_activism,
    'warehouse': Icons.warehouse,
    'wash': Icons.wash,
    'water': Icons.water,
    'water_drop': Icons.water_drop,
    'wb_sunny': Icons.wb_sunny,
    'wine_bar': Icons.wine_bar,
    'woman': Icons.woman,
    'work': Icons.work,
    'work_outline': Icons.work_outline,
    'yard': Icons.yard,
  };

  static IconData get(String? name) => _map[name] ?? Icons.category;

  static bool has(String name) => _map.containsKey(name);

  /// Özel liste tipi / kategori oluştururken seçilebilecek ikonlar (sıralı).
  static List<String> get pickerNames => _picker;

  static const List<String> _picker = [
    'list_alt',
    'checklist',
    'shopping_cart',
    'flight_takeoff',
    'outdoor_grill',
    'forest',
    'local_shipping',
    'child_friendly',
    'home',
    'work',
    'school',
    'fitness_center',
    'celebration',
    'cake',
    'park',
    'beach_access',
    'pool',
    'hiking',
    'backpack',
    'directions_car',
    'directions_bike',
    'directions_boat',
    'sports_soccer',
    'sports_tennis',
    'sports_basketball',
    'sports_golf',
    'music_note',
    'movie',
    'book',
    'menu_book',
    'brush',
    'palette',
    'build',
    'yard',
    'grass',
    'restaurant',
    'coffee',
    'wine_bar',
    'local_pizza',
    'lunch_dining',
    'pets',
    'cruelty_free',
    'spa',
    'medical_services',
    'local_hospital',
    'vaccines',
    'elderly',
    'stroller',
    'toys',
    'attractions',
    'festival',
    'storefront',
    'apartment',
    'villa',
    'garage',
    'local_laundry_service',
    'recycling',
    'event',
    'task_alt',
    'lightbulb',
    'bolt',
    'savings',
    'credit_card',
    'star',
    'favorite',
    'flag',
    'rocket_launch',
    'science',
    'computer',
    'smartphone',
    'headphones',
    'photo_camera',
    'videocam',
    'redeem',
    'card_giftcard',
    'church',
    'mosque',
    'volunteer_activism',
    'emoji_events',
    'category',
  ];
}
