# -*- coding: utf-8 -*-
"""Taşınma listesi: zaman çizelgesi odaklı görev listesi + malzeme + adres değişiklikleri."""
from common import *

FILTERS = [
    filt("distance", "Mesafe", "Nereye taşınıyorsunuz?",
         [opt("same_city", "Aynı şehir", "location_city"), opt("other_city", "Başka şehir", "map"), opt("abroad", "Yurt dışı", "public")], "same_city"),
    filt("home", "Konut", "Kiralık mı, kendi eviniz mi?",
         [opt("rent", "Kiracı", "key"), opt("own", "Ev sahibi", "home")], "rent"),
    filt("kids", "Çocuk", "Okul çağında çocuk var mı?", [opt("no", "Hayır"), opt("yes", "Evet", "school")], "no"),
    filt("mover", "Nakliye", "Taşımayı kim yapacak?",
         [opt("company", "Nakliye firması", "local_shipping"), opt("self", "Kendim / arkadaşlar", "groups")], "company"),
]
SECTIONS = [sec("tasks", "Görevler", "checklist"), sec("supplies", "Malzemeler", "inventory_2"), sec("address", "Adres ve Abonelikler", "badge")]
CATEGORIES = [
    cat("t8w",   "8-4 Hafta Önce",        "calendar_month",  C["indigo"],     "tasks"),
    cat("t2w",   "2 Hafta Önce",          "today",           C["blue"],       "tasks"),
    cat("t1w",   "Son Hafta",             "event_note",      C["cyan"],       "tasks"),
    cat("t1d",   "Bir Gün Önce",          "nightlight",      C["amber"],      "tasks"),
    cat("tday",  "Taşınma Günü",          "local_shipping",  C["red"],        "tasks"),
    cat("after", "Yeni Evde İlk Hafta",   "home_work",       C["green"],      "tasks"),
    cat("pack",  "Paketleme",             "inventory_2",     C["orange"],     "supplies"),
    cat("clean", "Temizlik",              "cleaning_services", C["teal"],     "supplies"),
    cat("tools", "Alet ve Kurulum",       "construction",    C["deeporange"], "supplies"),
    cat("firstnight", "İlk Gece Kutusu",  "bed",             C["purple"],     "supplies"),
    cat("utilities", "Abonelikler",       "subscriptions",   C["lightblue"],  "address"),
    cat("official",  "Resmi Adres Değişikliği", "badge",     C["red"],        "address"),
    cat("services",  "Hizmetler ve Üyelikler", "receipt_long", C["bluegrey"], "address"),
]
RENT = {"home": ["rent"]}; OWN = {"home": ["own"]}; KIDS = {"kids": ["yes"]}
COMPANY = {"mover": ["company"]}; SELF = {"mover": ["self"]}; FAR = {"distance": ["other_city", "abroad"]}; ABROAD = {"distance": ["abroad"]}
def t(id, name, cat_, days, when=None, essential=False, note=None):
    return item(id, name, cat_, when=when, daysBefore=days, essential=essential, note=note)

items = [
    # 8-4 hafta
    t("notice_landlord", "Ev sahibine yazılı çıkış bildirimi yap", "t8w", 45, when=RENT, essential=True, note="Sözleşmedeki bildirim süresine bakın (genelde 15-30 gün)."),
    t("get_quotes", "Nakliye firmalarından teklif al", "t8w", 40, when=COMPANY),
    t("book_mover", "Nakliye firmasını ayarla / sözleşme yap", "t8w", 30, when=COMPANY, essential=True),
    t("rent_van", "Kamyonet / araç kirala", "t8w", 21, when=SELF, essential=True),
    t("declutter", "Eşyaları ayıkla: sat / bağışla / at", "t8w", 35),
    t("inventory", "Eşya envanteri çıkar (fotoğraflı)", "t8w", 30),
    t("school_transfer", "Okul nakil işlemlerini başlat", "t8w", 45, when=KIDS, essential=True),
    t("job_notice", "İşyerine taşınma iznini bildir", "t8w", 30),
    t("budget", "Taşınma bütçesi belirle", "t8w", 40),
    t("new_home_measure", "Yeni evin ölçülerini al (mobilya sığacak mı?)", "t8w", 30),
    t("visa_docs", "Vize / oturma izni belgelerini hazırla", "t8w", 60, when=ABROAD, essential=True),
    t("intl_shipping", "Uluslararası nakliye / gümrük evraklarını araştır", "t8w", 50, when=ABROAD),
    # 2 hafta
    t("start_packing", "Az kullanılan eşyaları paketlemeye başla", "t2w", 14),
    t("label_system", "Kutu etiketleme sistemi belirle (oda + numara)", "t2w", 14),
    t("utilities_transfer", "Elektrik / su / doğalgaz / internet nakil başvurusu", "t2w", 14, essential=True),
    t("internet_new", "Yeni ev için internet başvurusu yap", "t2w", 14, note="Kurulum randevuları 1-2 hafta sürebilir."),
    t("elevator_booking", "Asansör / bina yönetimine bildirim", "t2w", 10),
    t("parking_permit", "Nakliye aracı için park yeri ayarla", "t2w", 7),
    t("new_home_clean", "Yeni evin temizliğini ayarla", "t2w", 7),
    t("new_home_repairs", "Yeni evde boya / tadilat / böcek ilaçlama", "t2w", 14, when=OWN),
    t("insurance", "Konut / eşya sigortasını güncelle", "t2w", 10),
    t("doctor_records", "Doktor / diş hekimi kayıtlarını al", "t2w", 14, when=FAR),
    t("pharmacy", "Reçeteli ilaçları yenile", "t2w", 7, when=FAR),
    t("bank_notice", "Bankaya adres güncelleme", "t2w", 10),
    # Son hafta
    t("pack_most", "Günlük kullanılmayan her şeyi paketle", "t1w", 5),
    t("first_night_box", "İlk gece kutusunu hazırla", "t1w", 3, essential=True),
    t("confirm_mover", "Nakliye firmasıyla saat ve adresi teyit et", "t1w", 2, when=COMPANY, essential=True),
    t("confirm_helpers", "Yardım edecek arkadaşları teyit et", "t1w", 3, when=SELF),
    t("empty_fridge", "Buzdolabını boşalt, buzluğu çöz", "t1w", 2),
    t("disassemble", "Mobilyaları sök (vidaları poşetle, etiketle)", "t1w", 2),
    t("valuables", "Değerli eşya ve belgeleri ayrı çantaya al", "t1w", 3, essential=True),
    t("cash", "Nakit para hazırla (bahşiş, beklenmedik masraf)", "t1w", 2),
    t("backup", "Bilgisayar / telefon yedeği al", "t1w", 3),
    t("appliance_prep", "Çamaşır makinesi nakliye vidalarını tak, su boşalt", "t1w", 1),
    t("kids_bag", "Çocuk için özel çanta (oyuncak, atıştırmalık, kıyafet)", "t1w", 2, when=KIDS),
    t("photo_old", "Eski evin fotoğraflarını çek (depozito için)", "t1w", 1, when=RENT),
    t("meter_reading_old", "Eski ev sayaç değerlerini oku ve fotoğrafla", "t1w", 1, essential=True),
    # Bir gün önce
    t("charge_devices", "Telefon ve powerbank şarj et", "t1d", 1),
    t("final_walkthrough_prep", "Dolap, çekmece, balkon, kiler son kontrol", "t1d", 1),
    t("keys_ready", "Yeni evin anahtarlarını teslim al", "t1d", 1, essential=True),
    t("route_plan", "Rota ve park planı", "t1d", 1),
    t("snacks_water", "Taşınma günü için su ve atıştırmalık", "t1d", 1),
    t("sleep_early", "Erken yat", "t1d", 1),
    # Taşınma günü
    t("protect_floors", "Zemin ve kapı korumaları ser", "tday", 0),
    t("supervise", "Yüklemeyi denetle, kırılacakları belirt", "tday", 0, when=COMPANY),
    t("inventory_check", "Kutu sayımını yap (yükleme ve boşaltmada)", "tday", 0, essential=True),
    t("final_walkthrough", "Eski evde son tur: pencere, musluk, ışık, kapı", "tday", 0, essential=True),
    t("hand_keys", "Eski ev anahtarlarını teslim et", "tday", 0, when=RENT),
    t("new_meter_reading", "Yeni ev sayaçlarını oku ve fotoğrafla", "tday", 0, essential=True),
    t("check_damage", "Yeni evde hasar kontrolü, fotoğrafla", "tday", 0),
    t("setup_beds", "Önce yatakları kur", "tday", 0),
    t("bathroom_first", "Banyo ve tuvaleti kullanılır hale getir", "tday", 0),
    t("pay_mover", "Nakliye ödemesi ve teslim tutanağı", "tday", 0, when=COMPANY),
    # İlk hafta
    t("unpack_kitchen", "Mutfağı yerleştir", "after", -2),
    t("locks", "Kilitleri değiştir", "after", -1, essential=True),
    t("smoke_detector", "Duman dedektörü / yangın tüpü kontrol", "after", -3),
    t("register_address", "Adres kaydını güncelle (e-Devlet / Nüfus)", "after", -7, essential=True),
    t("meet_neighbors", "Komşular ve site yönetimiyle tanış", "after", -5),
    t("find_essentials", "En yakın market, eczane, hastane, ulaşım", "after", -3),
    t("kids_school_start", "Çocuğun yeni okul kaydını tamamla", "after", -3, when=KIDS),
    t("deposit", "Depozito iadesini takip et", "after", -14, when=RENT),
    t("recycle_boxes", "Kutuları geri dönüştür / sat", "after", -14),
    t("thank_helpers", "Yardım edenlere teşekkür et", "after", -2, when=SELF),
    t("home_insurance_new", "Yeni ev için konut sigortası / DASK", "after", -7, essential=True),
    # Paketleme malzemeleri
    item("boxes_small", "Küçük kutu (kitap, ağır eşya)", "pack", qty=10, unit="adet"),
    item("boxes_medium", "Orta kutu", "pack", qty=15, unit="adet"),
    item("boxes_large", "Büyük kutu (hafif eşya)", "pack", qty=10, unit="adet"),
    item("wardrobe_box", "Askılı kıyafet kutusu", "pack", qty=2, unit="adet"),
    item("tape", "Koli bandı", "pack", qty=6, unit="adet", essential=True),
    item("tape_dispenser", "Bant kesici", "pack", qty=1),
    item("bubble_wrap", "Balonlu naylon", "pack", qty=1, unit="rulo"),
    item("packing_paper", "Ambalaj kağıdı / gazete", "pack", qty=1, unit="paket"),
    item("stretch_film", "Streç film (mobilya için)", "pack", qty=2, unit="rulo"),
    item("markers", "Kalın keçeli kalem", "pack", qty=3, unit="adet", essential=True),
    item("labels", "Renkli etiket / bant (oda kodu)", "pack", qty=1, unit="paket"),
    item("ziplock", "Kilitli poşet (vida, kablo)", "pack", qty=1, unit="paket"),
    item("blankets", "Battaniye / koruyucu örtü", "pack", qty=4, unit="adet"),
    item("garbage_bags", "Büyük çöp poşeti (yastık, yorgan)", "pack", qty=1, unit="rulo"),
    item("cable_ties", "Kablo bağı", "pack", qty=1, unit="paket"),
    item("box_cutter", "Maket bıçağı", "pack", qty=2, unit="adet"),
    item("mattress_bag", "Yatak kılıfı", "pack", qty=1),
    item("tv_box", "TV kutusu / koruyucu", "pack", qty=1),
    # Temizlik
    item("all_purpose", "Çok amaçlı temizleyici", "clean"), item("sponges", "Sünger ve bez", "clean"),
    item("mop_bucket", "Paspas ve kova", "clean"), item("broom", "Süpürge / faraş", "clean"),
    item("gloves", "Eldiven", "clean"), item("trash_bags_clean", "Çöp poşeti", "clean"),
    item("glass_cleaner", "Cam temizleyici", "clean"), item("bathroom_cleaner", "Banyo temizleyici", "clean"),
    item("vacuum", "Elektrikli süpürge (ulaşılabilir yerde)", "clean"), item("paper_towels", "Kağıt havlu", "clean"),
    # Alet
    item("screwdriver_set", "Tornavida seti", "tools", essential=True), item("allen_keys", "Alyan seti", "tools"),
    item("drill", "Matkap ve uçlar", "tools"), item("hammer", "Çekiç", "tools"),
    item("measuring_tape", "Şerit metre", "tools", essential=True), item("level", "Su terazisi", "tools"),
    item("wall_plugs", "Dübel ve vida", "tools"), item("pliers", "Pense", "tools"),
    item("furniture_sliders", "Mobilya kaydırıcı", "tools", when=SELF), item("dolly", "Taşıma arabası / el arabası", "tools", when=SELF),
    item("moving_straps", "Taşıma kayışı", "tools", when=SELF), item("work_gloves", "İş eldiveni", "tools", when=SELF),
    item("extension_cord", "Uzatma kablosu / çoklu priz", "tools"), item("flashlight", "El feneri", "tools"),
    item("step_ladder", "Merdiven", "tools"), item("picture_hooks", "Tablo askısı / çivi", "tools"),
    # İlk gece kutusu
    item("fn_bedding", "Çarşaf, yastık, yorgan", "firstnight", essential=True), item("fn_towels", "Havlu", "firstnight"),
    item("fn_toiletries", "Diş fırçası, sabun, şampuan, tuvalet kağıdı", "firstnight", essential=True),
    item("fn_clothes", "2 günlük kıyafet", "firstnight"), item("fn_chargers", "Şarj aletleri", "firstnight", essential=True),
    item("fn_meds", "İlaçlar", "firstnight", essential=True), item("fn_kettle", "Su ısıtıcı, bardak, çay / kahve", "firstnight"),
    item("fn_snacks", "Atıştırmalık ve su", "firstnight"), item("fn_paper_plates", "Kağıt tabak, plastik çatal", "firstnight"),
    item("fn_documents", "Önemli belgeler (kimlik, sözleşme, tapu)", "firstnight", essential=True),
    item("fn_tools", "Temel aletler (tornavida, maket bıçağı)", "firstnight"), item("fn_light", "Ampul / fener", "firstnight"),
    item("fn_kids", "Çocuğun sevdiği oyuncak, battaniye", "firstnight", when=KIDS, essential=True),
    item("fn_curtains", "Geçici perde / çarşaf", "firstnight"), item("fn_trash", "Çöp poşeti", "firstnight"),
    # Abonelikler
    item("u_electric", "Elektrik", "utilities", essential=True), item("u_water", "Su", "utilities", essential=True),
    item("u_gas", "Doğalgaz", "utilities", essential=True), item("u_internet", "İnternet", "utilities", essential=True),
    item("u_tv", "TV / dijital yayın", "utilities"), item("u_phone", "Sabit telefon", "utilities"),
    item("u_dues", "Site aidatı / yönetim kaydı", "utilities"), item("u_dask", "DASK / konut sigortası", "utilities", essential=True),
    # Resmi
    item("o_edevlet", "e-Devlet / Nüfus adres beyanı", "official", essential=True, note="Taşındıktan sonra 20 iş günü içinde."),
    item("o_bank", "Banka(lar)", "official"), item("o_tax", "Vergi dairesi", "official", when=OWN),
    item("o_vehicle", "Araç ruhsatı / ehliyet adresi", "official"), item("o_employer", "İşveren / SGK", "official"),
    item("o_school", "Okul / kreş", "official", when=KIDS), item("o_health", "Aile hekimi kaydı", "official"),
    item("o_embassy", "Konsolosluk / göç idaresi kaydı", "official", when=ABROAD, essential=True),
    item("o_voting", "Seçmen kaydı", "official"),
    # Hizmetler
    item("s_ecommerce", "Online alışveriş siteleri adresleri", "services"), item("s_subscriptions", "Dergi / kutu abonelikleri", "services"),
    item("s_gym", "Spor salonu üyeliği", "services"), item("s_delivery", "Yemek / market uygulamaları", "services"),
    item("s_courier", "Kargo firmaları adres defteri", "services"), item("s_insurance", "Sağlık / araç sigortası", "services"),
    item("s_streaming", "Kart bağlı abonelikler (fatura adresi)", "services"), item("s_mail_forward", "PTT adres yönlendirme", "services"),
    item("s_cleaner", "Temizlikçi / bakıcı bilgilendirme", "services"), item("s_friends", "Aile ve arkadaşlara yeni adres", "services"),
]

TEMPLATE = {
    "id": "tasinma", "name": "Taşınma",
    "description": "8 hafta öncesinden ilk haftaya: görevler, paketleme malzemeleri ve adres değişiklikleri.",
    "icon": "local_shipping", "color": "#6D4C41",
    "dateMode": "single", "dateLabel": "Taşınma günü", "endDateLabel": None,
    "textFields": [field("from", "Eski adres (semt)", ""), field("to", "Yeni adres (semt)", "")],
    "filters": FILTERS, "sections": SECTIONS, "categories": CATEGORIES, "items": items,
}
